export const weather_codes = {
	0: 'clear',
	1: 'mainly clear',
	2: 'partly cloudy',
	3: 'overcast',
	45: 'fog',
	48: 'fog',
	51: 'drizzle-light',
	53: 'drizzle-moderate',
	55: 'drizzle-dense',
	56: 'drizzle-freezing-light',
	57: 'drizzle-freezing-dense',
	61: 'rain-slight',
	63: 'rain-moderate',
	65: 'rain-heavy',
	66: 'rain-freezing-light',
	67: 'rain-freezing-heavy',
	71: 'snow-slight',
	73: 'snow-moderate',
	75: 'snow-heavy',
	77: 'snow-grains',
	80: 'rain showers-slight',
	81: 'rain showers-moderate',
	82: 'rain showers-violent',
	85: 'show showers-slight',
	86: 'show showers-heavy',
	95: 'thunderstorm',
	96: 'thunderstorm with hail-slight',
	99: 'thunderstorm with hail-heavy',
}

export default weather_codes
